#!/run/current-system/sw/bin/zsh

xfreerdp /u:MyWindowsUser /p:MyWindowsPassword /v:127.0.0.1 /cert:tofu /app:program:'C:\Program Files\WindowsApps\MSTeams_25306.804.4102.7193_x64__8wekyb3d8bbwe\ms-teams.exe'
